#!/usr/bin/env ruby

require 'rubygems'
require 'irb'
require 'pp'

require File.expand_path(File.dirname(__FILE__) + '/../spec/spec_helper')

if __FILE__ == $0
  IRB.start(__FILE__)
else
  # check -e option
  if /^-e$/ =~ $0
    IRB.start(__FILE__)
  else
    IRB.setup(__FILE__)
  end
end

